insert ignore into watercan.country (id,name,country_code) values (1,'India','IN');
insert ignore into watercan.state (id,name) values  (1,'TamilNadu');
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (1,'Adambakkam',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (2,'Adyar',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (3,'Alandur',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (4,'Anna Nagar',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (5,'Ashok Nagar',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (6,'Ayanavaram',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (7,'Chetpet',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (8,'Chitlapakkam',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (9,'Choolai',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (10,'Chromepet',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (11,'Egmore',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (12,'Guindy',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (13,'Injambakkam',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (14,'K. K. Nagar',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (15,'Kodambakkam',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (16,'Kodungaiyur',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (17,'Kolathur',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (18,'Korukkupet',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (19,'Madhavaram',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (20,'Mambalam',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (21,'Mannivakkam',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (22,'Medavakkam',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (23,'Meenambakkam',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (24,'Mudichur',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (25,'Mylapore',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (26,'New Washermenpet',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (27,'Nungambakkam',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (28,'Pallavaram',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (29,'Park Town',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (30,'Peerkankaranai',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (31,'Perambur',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (32,'Perungalathur',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (33,'Purasawalkam',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (34,'Saidapet',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (35,'Sembakkam',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (36,'Shenoy Nagar',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (37,'Sholinganallur',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (38,'T. Nagar',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (39,'Thiru. Vi. Ka Nagar',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (40,'Tharamani',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (41,'Thuraipakkam',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (42,'Tirusulam',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (43,'Tondiarpet',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (44,'Triplicane',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (45,'Vadapalani',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (46,'Vandalur',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (47,'Vyasarpadi',1);
INSERT ignore INTO watercan.city (id,name,state_id) VALUES (48,'Washermanpet',1);
